/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React, { useState } from 'react';
import { GeneratedImage } from '../types';
import { Download, Sparkles, Edit3, Maximize2, X, ZoomIn, ZoomOut, RefreshCcw, Share2, Copy, Check, Linkedin, Twitter, Image, Contrast, Printer, Presentation, Loader2, AlertCircle, ExternalLink } from 'lucide-react';
import { getGoogleAccessToken, signInWithGoogle } from '../services/firebaseService';
import { exportInfographicToGoogleSlides } from '../services/workspaceService';

interface InfographicProps {
  image: GeneratedImage;
  onEdit: (prompt: string) => void;
  isEditing: boolean;
  onRegenerate: () => void;
}

const base64ToBlob = (base64: string, mime: string = 'image/png') => {
  const cleanBase64 = base64.includes(',') ? base64.split(',')[1] : base64;
  const byteCharacters = atob(cleanBase64);
  const byteNumbers = new Array(byteCharacters.length);
  for (let i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
  }
  const byteArray = new Uint8Array(byteNumbers);
  return new Blob([byteArray], { type: mime });
};

const Infographic: React.FC<InfographicProps> = ({ image, onEdit, isEditing, onRegenerate }) => {
  const [editPrompt, setEditPrompt] = useState('');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [zoomLevel, setZoomLevel] = useState(1);
  const [showShareDropdown, setShowShareDropdown] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedImage, setCopiedImage] = useState(false);
  const [contrast, setContrast] = useState(100);
  const [includeWatermark, setIncludeWatermark] = useState(true);

  // Google Slides Export States
  const [isExporting, setIsExporting] = useState(false);
  const [exportSuccess, setExportSuccess] = useState<{
    presentationId: string;
    presentationUrl: string;
    driveFileId: string;
    driveFileUrl: string;
  } | null>(null);
  const [exportError, setExportError] = useState<string | null>(null);

  const handleExportToSlides = async () => {
    setIsExporting(true);
    setExportError(null);
    setExportSuccess(null);
    try {
      let token = getGoogleAccessToken();
      if (!token) {
        // Authenticate with Google Provider and Slides/Drive Scopes requested
        const confirmed = window.confirm(
          "Exporting to Google Slides requires Slides and Google Drive permissions. Connect your account now?"
        );
        if (!confirmed) {
          setIsExporting(false);
          return;
        }

        await signInWithGoogle();
        token = getGoogleAccessToken();
        if (!token) {
          throw new Error("Could not acquire Google access token. Please ensure your popups are enabled and try again.");
        }
      }

      // 1. Get processed image representation (contrast, watermark settings included)
      const processedUrl = await getProcessedImageDataUrl();
      
      // 2. Perform the full exported presentation generation on Slides and Drive
      const result = await exportInfographicToGoogleSlides(token, image, processedUrl);
      
      setExportSuccess(result);
    } catch (err: any) {
      console.error("Google Workspace Export failed:", err);
      // Clean up descriptive messages for better UX
      if (err.message && err.message.includes('popup')) {
        setExportError("Sign-in popup was blocked. Please allow popups for this site and retry.");
      } else {
        setExportError(err.message || String(err));
      }
    } finally {
      setIsExporting(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editPrompt.trim()) return;
    onEdit(editPrompt);
    setEditPrompt('');
  };

  const handleZoomIn = () => setZoomLevel(prev => Math.min(prev + 0.5, 4));
  const handleZoomOut = () => setZoomLevel(prev => Math.max(prev - 0.5, 0.5));
  const handleResetZoom = () => setZoomLevel(1);

  const handleCloseFullscreen = () => {
    setIsFullscreen(false);
    setZoomLevel(1);
  };

  const getProcessedImageDataUrl = async (): Promise<string> => {
    if (!includeWatermark && contrast === 100) {
      return image.data;
    }
    
    return new Promise((resolve) => {
      const img = new window.Image();
      img.crossOrigin = 'anonymous';
      img.src = image.data;
      img.onload = () => {
        const canvas = document.createElement('canvas');
        canvas.width = img.naturalWidth;
        canvas.height = img.naturalHeight;
        const ctx = canvas.getContext('2d');
        if (!ctx) {
          resolve(image.data);
          return;
        }

        // Apply contrast if it is not 100
        if (contrast !== 100) {
          ctx.filter = `contrast(${contrast}%)`;
        }

        ctx.drawImage(img, 0, 0);

        // Reset filter for watermark so it remains clear and pristine
        ctx.filter = 'none';

        if (includeWatermark) {
          const text = 'Generated by InfoGenius';
          const scale = img.naturalWidth / 1024;
          const fontSize = Math.max(Math.round(18 * scale), 12);
          const paddingX = Math.max(Math.round(16 * scale), 10);
          const paddingY = Math.max(Math.round(8 * scale), 6);
          const borderRadius = Math.max(Math.round(8 * scale), 4);
          const bottomMargin = Math.max(Math.round(24 * scale), 16);
          const rightMargin = Math.max(Math.round(24 * scale), 16);

          ctx.font = `600 ${fontSize}px system-ui, -apple-system, sans-serif`;
          const textMetrics = ctx.measureText(text);
          const textWidth = textMetrics.width;
          const textHeight = fontSize;

          const rectWidth = textWidth + paddingX * 2;
          const rectHeight = textHeight + paddingY * 2;
          const rectX = canvas.width - rectWidth - rightMargin;
          const rectY = canvas.height - rectHeight - bottomMargin;

          ctx.save();
          ctx.shadowColor = 'rgba(0, 0, 0, 0.4)';
          ctx.shadowBlur = Math.round(10 * scale);
          ctx.shadowOffsetX = 0;
          ctx.shadowOffsetY = Math.round(4 * scale);

          ctx.fillStyle = 'rgba(15, 23, 42, 0.9)';
          ctx.beginPath();
          ctx.moveTo(rectX + borderRadius, rectY);
          ctx.lineTo(rectX + rectWidth - borderRadius, rectY);
          ctx.quadraticCurveTo(rectX + rectWidth, rectY, rectX + rectWidth, rectY + borderRadius);
          ctx.lineTo(rectX + rectWidth, rectY + rectHeight - borderRadius);
          ctx.quadraticCurveTo(rectX + rectWidth, rectY + rectHeight, rectX + rectWidth - borderRadius, rectY + rectHeight);
          ctx.lineTo(rectX + borderRadius, rectY + rectHeight);
          ctx.quadraticCurveTo(rectX, rectY + rectHeight, rectX, rectY + rectHeight - borderRadius);
          ctx.lineTo(rectX, rectY + borderRadius);
          ctx.quadraticCurveTo(rectX, rectY, rectX + borderRadius, rectY);
          ctx.closePath();
          ctx.fill();

          ctx.strokeStyle = 'rgba(255, 255, 255, 0.15)';
          ctx.lineWidth = Math.max(1, Math.round(1 * scale));
          ctx.stroke();
          ctx.restore();

          ctx.fillStyle = '#f8fafc';
          ctx.textAlign = 'left';
          ctx.textBaseline = 'middle';
          ctx.fillText(text, rectX + paddingX, rectY + rectHeight / 2);
        }

        resolve(canvas.toDataURL('image/png'));
      };
      img.onerror = () => {
        resolve(image.data);
      };
    });
  };

  const handleDownload = async (e: React.MouseEvent) => {
    e.preventDefault();
    try {
      const processedUrl = await getProcessedImageDataUrl();
      const link = document.createElement('a');
      link.href = processedUrl;
      link.download = `infographic-${image.id || 'genius'}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    } catch (err) {
      console.error("Failed to download image", err);
    }
  };

  const getShareUrl = () => {
    const params = new URLSearchParams();
    params.set('topic', image.originalTopic || image.prompt);
    if (image.level) params.set('level', image.level);
    if (image.style) params.set('style', image.style);
    if (image.language) params.set('language', image.language);
    return `${window.location.origin}${window.location.pathname}?${params.toString()}`;
  };

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(getShareUrl());
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    } catch (err) {
      console.error("Failed to copy link", err);
    }
  };

  const handleCopyImage = async () => {
    try {
      const processedUrl = await getProcessedImageDataUrl();
      const blob = base64ToBlob(processedUrl, 'image/png');
      await navigator.clipboard.write([
        new ClipboardItem({
          [blob.type]: blob
        })
      ]);
      setCopiedImage(true);
      setTimeout(() => setCopiedImage(false), 2000);
    } catch (err) {
      console.error("Failed to copy image to clipboard", err);
    }
  };

  const isShareApiSupported = typeof navigator !== 'undefined' && !!navigator.share;
  
  const handleNativeShare = async () => {
    try {
      const url = getShareUrl();
      const title = `Infographic on ${image.originalTopic || image.prompt}`;
      const text = `Check out this amazing infographic about ${image.originalTopic || image.prompt} generated by InfoGenius Vision!`;
      
      if (navigator.canShare && navigator.canShare({ files: [] })) {
        const processedUrl = await getProcessedImageDataUrl();
        const blob = base64ToBlob(processedUrl, 'image/png');
        const file = new File([blob], `infographic-${image.id}.png`, { type: 'image/png' });
        await navigator.share({
          files: [file],
          title,
          text,
          url
        });
      } else {
        await navigator.share({
          title,
          text,
          url
        });
      }
    } catch (err) {
      console.error("Failed to share using native share API", err);
    }
  };

  const handleTwitterShare = () => {
    const shareUrl = getShareUrl();
    const text = encodeURIComponent(`Check out this interactive infographic about "${image.originalTopic || image.prompt}" generated with InfoGenius Vision! 🔮🎨`);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(shareUrl)}`;
    window.open(twitterUrl, '_blank', 'noopener,noreferrer');
  };

  const handleLinkedInShare = () => {
    const shareUrl = getShareUrl();
    const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`;
    window.open(linkedinUrl, '_blank', 'noopener,noreferrer');
  };

  const handlePrint = async () => {
    try {
      const processedUrl = await getProcessedImageDataUrl();
      
      // Create a hidden iframe
      const iframe = document.createElement('iframe');
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0';
      iframe.style.height = '0';
      iframe.style.border = '0';
      document.body.appendChild(iframe);
      
      const iframeDoc = iframe.contentWindow?.document || iframe.contentDocument;
      if (!iframeDoc) {
        throw new Error("Could not access iframe document");
      }
      
      iframeDoc.open();
      iframeDoc.write(`
        <html>
          <head>
            <title>Print Infographic - InfoGenius</title>
            <style>
              body {
                margin: 0;
                padding: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                min-height: 100vh;
                background: white;
              }
              img {
                max-width: 100%;
                max-height: 98vh;
                object-fit: contain;
              }
            </style>
          </head>
          <body>
            <img src="${processedUrl}" onload="setTimeout(() => { window.print(); }, 200);" />
          </body>
        </html>
      `);
      iframeDoc.close();
      
      // Clean up after standard delay (sufficient for the dialog to load)
      setTimeout(() => {
        if (iframe && iframe.parentNode) {
          document.body.removeChild(iframe);
        }
      }, 30000);
    } catch (err) {
      console.error("Failed to print infographic", err);
    }
  };

  return (
    <div className="flex flex-col items-center w-full max-w-6xl mx-auto animate-in fade-in zoom-in duration-700 mt-8">
      
      {/* Image Container */}
      <div className="relative group w-full bg-slate-100 dark:bg-slate-900 rounded-2xl overflow-hidden shadow-2xl border border-slate-200 dark:border-slate-700/50">
        {/* Decorative Corner Markers */}
        <div className="absolute top-0 left-0 w-16 h-16 border-t-2 border-l-2 border-cyan-500/30 rounded-tl-2xl z-20 pointer-events-none"></div>
        <div className="absolute top-0 right-0 w-16 h-16 border-t-2 border-r-2 border-cyan-500/30 rounded-tr-2xl z-20 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-16 h-16 border-b-2 border-l-2 border-cyan-500/30 rounded-bl-2xl z-20 pointer-events-none"></div>
        <div className="absolute bottom-0 right-0 w-16 h-16 border-b-2 border-r-2 border-cyan-500/30 rounded-br-2xl z-20 pointer-events-none"></div>

        <img 
          src={image.data} 
          alt={image.prompt} 
          onClick={() => setIsFullscreen(true)}
          style={{ filter: `contrast(${contrast}%)` }}
          className="w-full h-auto object-contain max-h-[80vh] bg-checkered relative z-10 cursor-zoom-in"
        />

        {/* Live Watermark Preview overlay */}
        {includeWatermark && (
          <div className="absolute bottom-4 right-4 sm:bottom-6 sm:right-6 z-30 bg-slate-950/90 backdrop-blur-md text-slate-100 px-3.5 py-2 rounded-xl text-[10px] sm:text-xs font-bold border border-white/10 shadow-xl pointer-events-none select-none tracking-wide">
            Generated by InfoGenius
          </div>
        )}

        {/* Contrast Slider floating widget */}
        <div className="absolute bottom-4 left-4 sm:bottom-6 sm:left-6 z-30 bg-black/60 backdrop-blur-md text-white px-3.5 py-2 rounded-xl shadow-lg border border-white/10 flex items-center gap-3 transition-all">
          <button 
            type="button" 
            onClick={() => setContrast(100)} 
            className="text-cyan-400 hover:text-cyan-300 transition-colors p-1" 
            title="Reset contrast to 100%"
          >
            <Contrast className="w-4 h-4" />
          </button>
          <div className="flex flex-col">
            <span className="text-[9px] font-bold tracking-widest uppercase text-slate-300">Contrast</span>
            <div className="flex items-center gap-2">
              <input 
                type="range" 
                min="50" 
                max="200" 
                value={contrast} 
                onChange={(e) => setContrast(Number(e.target.value))}
                className="w-20 sm:w-28 h-1 bg-slate-700 rounded-lg appearance-none cursor-pointer accent-cyan-455 hover:accent-cyan-400 focus:outline-none"
              />
              <span className="text-[10px] font-mono w-8 text-right font-bold text-cyan-300">{contrast}%</span>
            </div>
          </div>
        </div>
           {/* Hover Overlay for Quick Actions */}
        <div className="absolute top-6 right-6 flex gap-2 opacity-100 md:opacity-0 md:group-hover:opacity-100 transition-opacity z-30">
          <button 
            onClick={onRegenerate}
            disabled={isEditing}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block disabled:opacity-50 disabled:cursor-not-allowed"
            title="Regenerate Image"
          >
            <RefreshCcw className={`w-5 h-5 ${isEditing ? 'animate-spin' : ''}`} />
          </button>
          <button 
            onClick={() => setIsFullscreen(true)}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block"
            title="Fullscreen View"
          >
            <Maximize2 className="w-5 h-5" />
          </button>
          <button 
            onClick={handleDownload}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block cursor-pointer"
            title="Download Image"
          >
            <Download className="w-5 h-5" />
          </button>
          <button 
            onClick={handlePrint}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block cursor-pointer"
            title="Print Infographic"
          >
            <Printer className="w-5 h-5" />
          </button>
 
          {/* Quick Share Overlay Dropdown */}
          <div className="relative">
            <button 
              onClick={() => setShowShareDropdown(!showShareDropdown)}
              className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block"
              title="Share Image Choices"
            >
              <Share2 className="w-5 h-5" />
            </button>
            
            {showShareDropdown && (
              <>
                <div 
                  className="fixed inset-0 z-40 bg-transparent" 
                  onClick={() => setShowShareDropdown(false)}
                ></div>
                <div className="absolute right-0 mt-2 w-56 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-2xl p-2 z-50 flex flex-col gap-1 text-left animate-in fade-in slide-in-from-top-2 duration-200 text-slate-800 dark:text-slate-200">
                  <button 
                    onClick={() => { handleCopyLink(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-500 shrink-0" /> : <Copy className="w-3.5 h-3.5 shrink-0" />}
                    <span>{copiedLink ? "Link Copied!" : "Copy Link"}</span>
                  </button>
                  <button 
                    onClick={() => { handleCopyImage(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    {copiedImage ? <Check className="w-3.5 h-3.5 text-emerald-500 shrink-0" /> : <Image className="w-3.5 h-3.5 shrink-0" />}
                    <span>{copiedImage ? "Image Copied!" : "Copy PNG Image"}</span>
                  </button>
                  <button 
                    onClick={() => { handlePrint(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    <Printer className="w-3.5 h-3.5 text-cyan-555 shrink-0" />
                    <span>Print Infographic</span>
                  </button>
                  <button 
                    onClick={() => { handleExportToSlides(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2 text-amber-600 dark:text-amber-400"
                  >
                    <Presentation className="w-3.5 h-3.5 text-amber-500 shrink-0" />
                    <span>Export to Google Slides</span>
                  </button>
                  <button 
                    onClick={() => { handleTwitterShare(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    <Twitter className="w-3.5 h-3.5 text-sky-500 shrink-0" />
                    <span>Share to X (Twitter)</span>
                  </button>
                  <button 
                    onClick={() => { handleLinkedInShare(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    <Linkedin className="w-3.5 h-3.5 text-blue-600 shrink-0" />
                    <span>Share on LinkedIn</span>
                  </button>
                  {isShareApiSupported && (
                    <button 
                      onClick={() => { handleNativeShare(); setShowShareDropdown(false); }}
                      className="w-full text-left px-3 py-2 text-xs font-semibold text-cyan-500 border-t border-slate-100 dark:border-white/5 mt-1 pt-2 hover:bg-cyan-50/10 rounded-lg flex items-center gap-2"
                    >
                      <Share2 className="w-3.5 h-3.5 shrink-0" />
                      <span>Device Sharing Sheet</span>
                    </button>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Edit Bar */}
      <div className="w-full max-w-3xl -mt-6 sm:-mt-8 relative z-40 px-4">
        <div className="bg-white/90 dark:bg-slate-800/80 backdrop-blur-xl p-3 sm:p-2 sm:pr-3 rounded-2xl shadow-2xl border border-slate-200 dark:border-white/10 flex flex-col sm:flex-row gap-2 items-center ring-1 ring-black/5 dark:ring-white/5">
            <div className="pl-4 text-cyan-600 dark:text-cyan-400 hidden sm:block">
                <Edit3 className="w-5 h-5" />
            </div>
            <form onSubmit={handleSubmit} className="flex-1 w-full flex flex-col sm:flex-row gap-2">
                <input
                    type="text"
                    value={editPrompt}
                    onChange={(e) => setEditPrompt(e.target.value)}
                    placeholder="Refine the visual (e.g., 'Make the background stars')..."
                    className="flex-1 bg-slate-50 dark:bg-slate-950/50 sm:bg-transparent border border-slate-200 dark:border-white/5 sm:border-none rounded-xl sm:rounded-none focus:ring-0 text-slate-900 dark:text-white placeholder:text-slate-400 px-4 py-3 sm:px-2 sm:py-2 font-medium text-base"
                    disabled={isEditing}
                />
                
                {/* Wrapped button in div to allow tooltip on disabled state */}
                <div className="w-full sm:w-auto" title={!editPrompt.trim() ? "Please enter a prompt to enhance" : "Enhance image"}>
                    <button
                        type="submit"
                        disabled={isEditing || !editPrompt.trim()}
                        className={`w-full sm:w-auto px-5 py-3 sm:py-2.5 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                            isEditing || !editPrompt.trim() 
                            ? 'bg-slate-200 dark:bg-slate-700/50 text-slate-400 dark:text-slate-500 cursor-not-allowed' 
                            : 'bg-cyan-600 text-white hover:bg-cyan-500 shadow-lg shadow-cyan-500/20'
                        }`}
                    >
                        {isEditing ? (
                            <span className="animate-spin w-5 h-5 block border-2 border-white/30 border-t-white rounded-full"></span>
                        ) : (
                            <>
                                <span>Enhance</span>
                                <Sparkles className="w-4 h-4" />
                            </>
                        )}
                    </button>
                </div>

                {/* Regenerate Button */}
                <div className="w-full sm:w-auto" title="Generate an alternative design for this topic">
                    <button
                        type="button"
                        onClick={onRegenerate}
                        disabled={isEditing}
                        className={`w-full sm:w-auto px-5 py-3 sm:py-2.5 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                            isEditing
                            ? 'bg-slate-200 dark:bg-slate-700/50 text-slate-400 dark:text-slate-500 cursor-not-allowed' 
                            : 'bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-200'
                        }`}
                    >
                        {isEditing ? (
                            <span className="animate-spin w-5 h-5 block border-2 border-slate-400/30 border-t-slate-500 rounded-full"></span>
                        ) : (
                            <>
                                <span>Regenerate</span>
                                <RefreshCcw className="w-4 h-4" />
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
      </div>
      
      {/* Social Sharing & Info Panel */}
      <div className="w-full max-w-3xl mt-6 px-4">
        <div className="bg-white/80 dark:bg-slate-900/60 backdrop-blur-xl border border-slate-200 dark:border-white/10 rounded-2xl p-5 md:p-6 shadow-xl space-y-5 transition-colors">
          
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-150 dark:border-white/5 pb-4">
            <div className="text-left">
              <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Active Subject</h4>
              <p className="text-sm font-semibold text-slate-800 dark:text-slate-200 line-clamp-2 leading-snug">
                {image.originalTopic || image.prompt}
              </p>
            </div>
            {image.level && (
              <div className="flex flex-wrap gap-1.5 shrink-0">
                <span className="text-[10px] font-bold tracking-wider text-cyan-600 dark:text-cyan-400 bg-cyan-50 dark:bg-cyan-950/40 px-2.5 py-1 rounded-full border border-cyan-500/15">
                  {image.level}
                </span>
                {image.style && (
                  <span className="text-[10px] font-bold tracking-wider text-purple-600 dark:text-purple-400 bg-purple-50 dark:bg-purple-950/40 px-2.5 py-1 rounded-full border border-purple-500/15">
                    {image.style}
                  </span>
                )}
                {image.language && (
                  <span className="text-[10px] font-bold tracking-wider text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-950/40 px-2.5 py-1 rounded-full border border-green-500/15">
                    {image.language}
                  </span>
                )}
              </div>
            )}
          </div>

          <div className="space-y-3">
            <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest text-left">Share & Export</h4>
            
            {/* Watermark Toggle */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-slate-50/50 dark:bg-slate-950/20 p-4 rounded-xl border border-slate-100 dark:border-white/5 text-left mb-2">
              <div className="flex items-center gap-2.5">
                <span className="p-2 bg-slate-100 dark:bg-slate-850 text-cyan-500 rounded-lg shrink-0">
                  <Sparkles className="w-4 h-4" />
                </span>
                <div>
                  <p className="text-xs font-bold text-slate-800 dark:text-slate-200">Include Official Watermark</p>
                  <p className="text-[10px] text-slate-500 dark:text-slate-400 leading-normal">Adds an elegant "Generated by InfoGenius" badge to saved & copied PNG images</p>
                </div>
              </div>
              
              <label className="relative inline-flex items-center cursor-pointer select-none shrink-0">
                <input 
                  type="checkbox" 
                  checked={includeWatermark}
                  onChange={(e) => setIncludeWatermark(e.target.checked)}
                  className="sr-only peer"
                />
                <div className="w-11 h-6 bg-slate-200 dark:bg-slate-800 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-slate-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-cyan-650 dark:peer-checked:bg-cyan-600"></div>
              </label>
            </div>

            <div className="grid grid-cols-2 sm:grid-cols-5 gap-3">
              {/* Copy Link */}
              <button
                onClick={handleCopyLink}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-cyan-500/40 dark:hover:border-cyan-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-cyan-50/25 dark:hover:bg-cyan-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                {copiedLink ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-500 scale-110 shrink-0" />
                    <span className="text-emerald-600 dark:text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 text-slate-400 group-hover:text-cyan-550 dark:group-hover:text-cyan-400 transition-colors shrink-0" />
                    <span>Copy Link</span>
                  </>
                )}
              </button>

              {/* Copy Image */}
              <button
                onClick={handleCopyImage}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-cyan-500/40 dark:hover:border-cyan-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-cyan-50/25 dark:hover:bg-cyan-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                {copiedImage ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-500 scale-110 shrink-0" />
                    <span className="text-emerald-600 dark:text-emerald-400">Copied Image</span>
                  </>
                ) : (
                  <>
                    <Image className="w-4 h-4 text-slate-400 group-hover:text-cyan-550 dark:group-hover:text-cyan-400 transition-colors shrink-0" />
                    <span>Copy Image</span>
                  </>
                )}
              </button>

              {/* Export to Google Slides */}
              <button
                onClick={handleExportToSlides}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-amber-500/40 dark:hover:border-amber-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-amber-55/25 dark:hover:bg-amber-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
                title="Export this Infographic to a Google Slides presentation"
              >
                <Presentation className="w-4 h-4 text-slate-400 group-hover:text-amber-500 transition-colors shrink-0" />
                <span>Google Slides</span>
              </button>

              {/* Print Infographic */}
              <button
                onClick={handlePrint}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-cyan-500/40 dark:hover:border-cyan-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-cyan-50/25 dark:hover:bg-cyan-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
                title="Print the Infographic on Paper or as PDF"
              >
                <Printer className="w-4 h-4 text-slate-400 group-hover:text-cyan-550 dark:group-hover:text-cyan-400 transition-colors shrink-0" />
                <span>Print</span>
              </button>

              {/* Share X */}
              <button
                onClick={handleTwitterShare}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-sky-500/40 dark:hover:border-sky-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-sky-50/25 dark:hover:bg-sky-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                <Twitter className="w-4 h-4 text-slate-400 group-hover:text-sky-500 transition-colors shrink-0" />
                <span>Share to X</span>
              </button>

              {/* Share LinkedIn */}
              <button
                onClick={handleLinkedInShare}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-blue-500/40 dark:hover:border-blue-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-blue-50/25 dark:hover:bg-blue-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                <Linkedin className="w-4 h-4 text-slate-400 group-hover:text-blue-500 transition-colors shrink-0" />
                <span>LinkedIn</span>
              </button>
            </div>

            {isShareApiSupported && (
              <button
                onClick={handleNativeShare}
                className="w-full mt-2 flex items-center gap-2 justify-center py-2.5 rounded-xl border border-dashed border-slate-200 dark:border-white/15 text-xs text-slate-500 hover:text-cyan-500 dark:text-slate-400 dark:hover:text-cyan-400 bg-transparent hover:bg-cyan-50/10 transition-all cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                <span>Use Device Native sharing option</span>
              </button>
            )}
          </div>

          <div className="text-center pt-2">
            <p className="text-[10px] text-slate-500 dark:text-slate-500 font-mono max-w-xl mx-auto truncate opacity-60">
              PROMPT: {image.prompt}
            </p>
          </div>

        </div>
      </div>

      {/* Fullscreen Modal */}
      {isFullscreen && (
        <div className="fixed inset-0 z-[100] bg-slate-100/95 dark:bg-slate-950/95 backdrop-blur-xl flex flex-col animate-in fade-in duration-300">
            {/* Toolbar */}
            <div className="absolute top-0 left-0 right-0 p-4 flex justify-between items-center z-50 pointer-events-none">
                <div className="flex gap-2 pointer-events-auto bg-white/10 backdrop-blur-md p-1 rounded-lg border border-black/5 dark:border-white/10">
                    <button onClick={handleZoomOut} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Zoom Out">
                        <ZoomOut className="w-5 h-5" />
                    </button>
                    <button onClick={handleResetZoom} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Reset Zoom">
                        <span className="text-xs font-bold">{Math.round(zoomLevel * 100)}%</span>
                    </button>
                    <button onClick={handleZoomIn} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Zoom In">
                        <ZoomIn className="w-5 h-5" />
                    </button>
                </div>

                <button 
                    onClick={handleCloseFullscreen}
                    className="pointer-events-auto p-3 bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-white rounded-full hover:bg-slate-300 dark:hover:bg-slate-700 transition-colors shadow-lg"
                >
                    <X className="w-6 h-6" />
                </button>
            </div>

            <div className="flex-1 overflow-auto flex items-center justify-center p-4 sm:p-8">
                <img 
                    src={image.data} 
                    alt={image.prompt}
                    style={{ 
                        transform: `scale(${zoomLevel})`,
                        filter: `contrast(${contrast}%)`,
                        transition: 'transform 0.2s ease-out'
                    }}
                    className="max-w-full max-h-full object-contain shadow-2xl rounded-lg origin-center"
                />
            </div>
        </div>
      )}

      {/* Google Slides Export Feedback Modal */}
      {(isExporting || exportSuccess || exportError) && (
        <div className="fixed inset-0 z-[110] bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4 animate-in fade-in duration-200">
          <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-white/10 rounded-3xl shadow-2xl p-6 sm:p-8 max-w-sm sm:max-w-md w-full relative overflow-hidden animate-in zoom-in-95 duration-200">
            {/* Background design accents */}
            <div className="absolute top-0 left-0 right-0 h-1.5 bg-gradient-to-r from-amber-500 to-yellow-400"></div>
            
            <button 
              onClick={() => { setIsExporting(false); setExportSuccess(null); setExportError(null); }}
              className="absolute top-4 right-4 p-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
              title="Close Modal"
              disabled={isExporting}
            >
              <X className="w-5 h-5" />
            </button>

            {isExporting && (
              <div className="flex flex-col items-center justify-center text-center py-6 gap-4 animate-pulse">
                <div className="relative">
                  <div className="w-16 h-16 rounded-full bg-amber-500/10 dark:bg-amber-500/20 flex items-center justify-center text-amber-500">
                    <Presentation className="w-8 h-8 pointer-events-none" />
                  </div>
                  <Loader2 className="w-6 h-6 text-amber-500 animate-spin absolute -bottom-1 -right-1" />
                </div>
                <div className="space-y-1">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">Exporting Infographic</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400">
                    Generating your high-resolution Google Slides presentation in your workspace...
                  </p>
                </div>
                <div className="w-full bg-slate-100 dark:bg-slate-800 h-1 rounded-full overflow-hidden">
                  <div className="bg-amber-500 h-full w-2/3 rounded-full animate-bounce"></div>
                </div>
              </div>
            )}

            {exportError && (
              <div className="flex flex-col items-center justify-center text-center py-4 gap-4">
                <div className="w-16 h-16 rounded-full bg-rose-500/10 dark:bg-rose-500/20 flex items-center justify-center text-rose-500">
                  <AlertCircle className="w-8 h-8" />
                </div>
                <div className="space-y-1">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">Export Failed</h3>
                  <p className="text-xs text-rose-600 dark:text-rose-400 text-left bg-rose-50 dark:bg-rose-950/20 p-3 rounded-xl max-h-32 overflow-y-auto w-full font-mono border border-rose-100 dark:border-rose-950/50">
                    {exportError}
                  </p>
                </div>
                <div className="flex gap-2 w-full mt-2">
                  <button
                    onClick={handleExportToSlides}
                    className="flex-1 bg-amber-500 hover:bg-amber-600 text-white font-bold py-2.5 px-4 rounded-xl text-sm transition-colors cursor-pointer"
                  >
                    Retry Export
                  </button>
                  <button
                    onClick={() => setExportError(null)}
                    className="flex-1 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold py-2.5 px-4 rounded-xl text-sm transition-colors cursor-pointer"
                  >
                    Close
                  </button>
                </div>
              </div>
            )}

            {exportSuccess && (
              <div className="flex flex-col items-center justify-center text-center py-4 gap-4 font-sans">
                <div className="w-16 h-16 rounded-full bg-emerald-500/10 dark:bg-emerald-500/20 flex items-center justify-center text-emerald-500">
                  <Check className="w-8 h-8 scale-110" />
                </div>
                <div className="space-y-1">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">Presentation Ready!</h3>
                  <p className="text-sm text-slate-500 dark:text-slate-400 animate-[fade-in_0.5s_ease]">
                    Your dynamic infographic was successfully processed and packaged in Google Slides.
                  </p>
                </div>
                
                <div className="w-full space-y-2 mt-2">
                  <a
                    href={exportSuccess.presentationUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-full flex items-center justify-center gap-2 bg-amber-500 hover:bg-amber-600 text-white font-bold py-3 px-4 rounded-xl text-sm shadow-md transition-colors cursor-pointer"
                  >
                    <Presentation className="w-4 h-4 shrink-0" />
                    <span>Open Google Slides</span>
                    <ExternalLink className="w-3.5 h-3.5 shrink-0 opacity-80" />
                  </a>

                  <a
                    href={exportSuccess.driveFileUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="w-full flex items-center justify-center gap-2 bg-slate-100 hover:bg-slate-200 dark:bg-slate-800 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-300 font-semibold py-2.5 px-4 rounded-xl text-sm transition-colors cursor-pointer"
                  >
                    <Image className="w-4 h-4 shrink-0 text-slate-400" />
                    <span>View Image in Drive</span>
                    <ExternalLink className="w-3.5 h-3.5 shrink-0 opacity-80" />
                  </a>
                </div>

                <button
                  onClick={() => setExportSuccess(null)}
                  className="mt-2 text-slate-400 hover:text-slate-600 dark:hover:text-slate-300 text-xs font-semibold cursor-pointer"
                >
                  Dismiss
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};

export default Infographic;