/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import React, { useState } from 'react';
import { GeneratedImage } from '../types';
import { Download, Sparkles, Edit3, Maximize2, X, ZoomIn, ZoomOut, RefreshCcw, Share2, Copy, Check, Linkedin, Twitter, Image } from 'lucide-react';

interface InfographicProps {
  image: GeneratedImage;
  onEdit: (prompt: string) => void;
  isEditing: boolean;
  onRegenerate: () => void;
}

const base64ToBlob = (base64: string, mime: string = 'image/png') => {
  const cleanBase64 = base64.includes(',') ? base64.split(',')[1] : base64;
  const byteCharacters = atob(cleanBase64);
  const byteNumbers = new Array(byteCharacters.length);
  for (let i = 0; i < byteCharacters.length; i++) {
    byteNumbers[i] = byteCharacters.charCodeAt(i);
  }
  const byteArray = new Uint8Array(byteNumbers);
  return new Blob([byteArray], { type: mime });
};

const Infographic: React.FC<InfographicProps> = ({ image, onEdit, isEditing, onRegenerate }) => {
  const [editPrompt, setEditPrompt] = useState('');
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [zoomLevel, setZoomLevel] = useState(1);
  const [showShareDropdown, setShowShareDropdown] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  const [copiedImage, setCopiedImage] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!editPrompt.trim()) return;
    onEdit(editPrompt);
    setEditPrompt('');
  };

  const handleZoomIn = () => setZoomLevel(prev => Math.min(prev + 0.5, 4));
  const handleZoomOut = () => setZoomLevel(prev => Math.max(prev - 0.5, 0.5));
  const handleResetZoom = () => setZoomLevel(1);

  const handleCloseFullscreen = () => {
    setIsFullscreen(false);
    setZoomLevel(1);
  }

  const getShareUrl = () => {
    const params = new URLSearchParams();
    params.set('topic', image.originalTopic || image.prompt);
    if (image.level) params.set('level', image.level);
    if (image.style) params.set('style', image.style);
    if (image.language) params.set('language', image.language);
    return `${window.location.origin}${window.location.pathname}?${params.toString()}`;
  };

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(getShareUrl());
      setCopiedLink(true);
      setTimeout(() => setCopiedLink(false), 2000);
    } catch (err) {
      console.error("Failed to copy link", err);
    }
  };

  const handleCopyImage = async () => {
    try {
      const blob = base64ToBlob(image.data, 'image/png');
      await navigator.clipboard.write([
        new ClipboardItem({
          [blob.type]: blob
        })
      ]);
      setCopiedImage(true);
      setTimeout(() => setCopiedImage(false), 2000);
    } catch (err) {
      console.error("Failed to copy image to clipboard", err);
    }
  };

  const isShareApiSupported = typeof navigator !== 'undefined' && !!navigator.share;
  
  const handleNativeShare = async () => {
    try {
      const url = getShareUrl();
      const title = `Infographic on ${image.originalTopic || image.prompt}`;
      const text = `Check out this amazing infographic about ${image.originalTopic || image.prompt} generated by InfoGenius Vision!`;
      
      if (navigator.canShare && navigator.canShare({ files: [] })) {
        const blob = base64ToBlob(image.data, 'image/png');
        const file = new File([blob], `infographic-${image.id}.png`, { type: 'image/png' });
        await navigator.share({
          files: [file],
          title,
          text,
          url
        });
      } else {
        await navigator.share({
          title,
          text,
          url
        });
      }
    } catch (err) {
      console.error("Failed to share using native share API", err);
    }
  };

  const handleTwitterShare = () => {
    const shareUrl = getShareUrl();
    const text = encodeURIComponent(`Check out this interactive infographic about "${image.originalTopic || image.prompt}" generated with InfoGenius Vision! 🔮🎨`);
    const twitterUrl = `https://twitter.com/intent/tweet?text=${text}&url=${encodeURIComponent(shareUrl)}`;
    window.open(twitterUrl, '_blank', 'noopener,noreferrer');
  };

  const handleLinkedInShare = () => {
    const shareUrl = getShareUrl();
    const linkedinUrl = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}`;
    window.open(linkedinUrl, '_blank', 'noopener,noreferrer');
  };

  return (
    <div className="flex flex-col items-center w-full max-w-6xl mx-auto animate-in fade-in zoom-in duration-700 mt-8">
      
      {/* Image Container */}
      <div className="relative group w-full bg-slate-100 dark:bg-slate-900 rounded-2xl overflow-hidden shadow-2xl border border-slate-200 dark:border-slate-700/50">
        {/* Decorative Corner Markers */}
        <div className="absolute top-0 left-0 w-16 h-16 border-t-2 border-l-2 border-cyan-500/30 rounded-tl-2xl z-20 pointer-events-none"></div>
        <div className="absolute top-0 right-0 w-16 h-16 border-t-2 border-r-2 border-cyan-500/30 rounded-tr-2xl z-20 pointer-events-none"></div>
        <div className="absolute bottom-0 left-0 w-16 h-16 border-b-2 border-l-2 border-cyan-500/30 rounded-bl-2xl z-20 pointer-events-none"></div>
        <div className="absolute bottom-0 right-0 w-16 h-16 border-b-2 border-r-2 border-cyan-500/30 rounded-br-2xl z-20 pointer-events-none"></div>

        <img 
          src={image.data} 
          alt={image.prompt} 
          onClick={() => setIsFullscreen(true)}
          className="w-full h-auto object-contain max-h-[80vh] bg-checkered relative z-10 cursor-zoom-in"
        />
        
        {/* Hover Overlay for Quick Actions */}
        <div className="absolute top-6 right-6 flex gap-2 opacity-100 md:opacity-0 md:group-hover:opacity-100 transition-opacity z-30">
          <button 
            onClick={onRegenerate}
            disabled={isEditing}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block disabled:opacity-50 disabled:cursor-not-allowed"
            title="Regenerate Image"
          >
            <RefreshCcw className={`w-5 h-5 ${isEditing ? 'animate-spin' : ''}`} />
          </button>
          <button 
            onClick={() => setIsFullscreen(true)}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block"
            title="Fullscreen View"
          >
            <Maximize2 className="w-5 h-5" />
          </button>
          <a 
            href={image.data} 
            download={`infographic-${image.id}.png`}
            className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block"
            title="Download Image"
          >
            <Download className="w-5 h-5" />
          </a>

          {/* Quick Share Overlay Dropdown */}
          <div className="relative">
            <button 
              onClick={() => setShowShareDropdown(!showShareDropdown)}
              className="bg-black/60 backdrop-blur-md text-white p-3 rounded-xl shadow-lg hover:bg-cyan-600 transition-colors border border-white/10 block"
              title="Share Image Choices"
            >
              <Share2 className="w-5 h-5" />
            </button>
            
            {showShareDropdown && (
              <>
                <div 
                  className="fixed inset-0 z-40 bg-transparent" 
                  onClick={() => setShowShareDropdown(false)}
                ></div>
                <div className="absolute right-0 mt-2 w-56 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl shadow-2xl p-2 z-50 flex flex-col gap-1 text-left animate-in fade-in slide-in-from-top-2 duration-200 text-slate-800 dark:text-slate-200">
                  <button 
                    onClick={() => { handleCopyLink(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    {copiedLink ? <Check className="w-3.5 h-3.5 text-emerald-500 shrink-0" /> : <Copy className="w-3.5 h-3.5 shrink-0" />}
                    <span>{copiedLink ? "Link Copied!" : "Copy Link"}</span>
                  </button>
                  <button 
                    onClick={() => { handleCopyImage(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    {copiedImage ? <Check className="w-3.5 h-3.5 text-emerald-500 shrink-0" /> : <Image className="w-3.5 h-3.5 shrink-0" />}
                    <span>{copiedImage ? "Image Copied!" : "Copy PNG Image"}</span>
                  </button>
                  <button 
                    onClick={() => { handleTwitterShare(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    <Twitter className="w-3.5 h-3.5 text-sky-500 shrink-0" />
                    <span>Share to X (Twitter)</span>
                  </button>
                  <button 
                    onClick={() => { handleLinkedInShare(); setShowShareDropdown(false); }}
                    className="w-full text-left px-3 py-2 text-xs font-semibold hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg flex items-center gap-2"
                  >
                    <Linkedin className="w-3.5 h-3.5 text-blue-600 shrink-0" />
                    <span>Share on LinkedIn</span>
                  </button>
                  {isShareApiSupported && (
                    <button 
                      onClick={() => { handleNativeShare(); setShowShareDropdown(false); }}
                      className="w-full text-left px-3 py-2 text-xs font-semibold text-cyan-500 border-t border-slate-100 dark:border-white/5 mt-1 pt-2 hover:bg-cyan-50/10 rounded-lg flex items-center gap-2"
                    >
                      <Share2 className="w-3.5 h-3.5 shrink-0" />
                      <span>Device Sharing Sheet</span>
                    </button>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      </div>

      {/* Edit Bar */}
      <div className="w-full max-w-3xl -mt-6 sm:-mt-8 relative z-40 px-4">
        <div className="bg-white/90 dark:bg-slate-800/80 backdrop-blur-xl p-3 sm:p-2 sm:pr-3 rounded-2xl shadow-2xl border border-slate-200 dark:border-white/10 flex flex-col sm:flex-row gap-2 items-center ring-1 ring-black/5 dark:ring-white/5">
            <div className="pl-4 text-cyan-600 dark:text-cyan-400 hidden sm:block">
                <Edit3 className="w-5 h-5" />
            </div>
            <form onSubmit={handleSubmit} className="flex-1 w-full flex flex-col sm:flex-row gap-2">
                <input
                    type="text"
                    value={editPrompt}
                    onChange={(e) => setEditPrompt(e.target.value)}
                    placeholder="Refine the visual (e.g., 'Make the background stars')..."
                    className="flex-1 bg-slate-50 dark:bg-slate-950/50 sm:bg-transparent border border-slate-200 dark:border-white/5 sm:border-none rounded-xl sm:rounded-none focus:ring-0 text-slate-900 dark:text-white placeholder:text-slate-400 px-4 py-3 sm:px-2 sm:py-2 font-medium text-base"
                    disabled={isEditing}
                />
                
                {/* Wrapped button in div to allow tooltip on disabled state */}
                <div className="w-full sm:w-auto" title={!editPrompt.trim() ? "Please enter a prompt to enhance" : "Enhance image"}>
                    <button
                        type="submit"
                        disabled={isEditing || !editPrompt.trim()}
                        className={`w-full sm:w-auto px-5 py-3 sm:py-2.5 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                            isEditing || !editPrompt.trim() 
                            ? 'bg-slate-200 dark:bg-slate-700/50 text-slate-400 dark:text-slate-500 cursor-not-allowed' 
                            : 'bg-cyan-600 text-white hover:bg-cyan-500 shadow-lg shadow-cyan-500/20'
                        }`}
                    >
                        {isEditing ? (
                            <span className="animate-spin w-5 h-5 block border-2 border-white/30 border-t-white rounded-full"></span>
                        ) : (
                            <>
                                <span>Enhance</span>
                                <Sparkles className="w-4 h-4" />
                            </>
                        )}
                    </button>
                </div>

                {/* Regenerate Button */}
                <div className="w-full sm:w-auto" title="Generate an alternative design for this topic">
                    <button
                        type="button"
                        onClick={onRegenerate}
                        disabled={isEditing}
                        className={`w-full sm:w-auto px-5 py-3 sm:py-2.5 rounded-xl font-bold flex items-center justify-center gap-2 transition-all ${
                            isEditing
                            ? 'bg-slate-200 dark:bg-slate-700/50 text-slate-400 dark:text-slate-500 cursor-not-allowed' 
                            : 'bg-slate-100 dark:bg-slate-700 hover:bg-slate-200 dark:hover:bg-slate-600 border border-slate-200 dark:border-white/10 text-slate-700 dark:text-slate-200'
                        }`}
                    >
                        {isEditing ? (
                            <span className="animate-spin w-5 h-5 block border-2 border-slate-400/30 border-t-slate-500 rounded-full"></span>
                        ) : (
                            <>
                                <span>Regenerate</span>
                                <RefreshCcw className="w-4 h-4" />
                            </>
                        )}
                    </button>
                </div>
            </form>
        </div>
      </div>
      
      {/* Social Sharing & Info Panel */}
      <div className="w-full max-w-3xl mt-6 px-4">
        <div className="bg-white/80 dark:bg-slate-900/60 backdrop-blur-xl border border-slate-200 dark:border-white/10 rounded-2xl p-5 md:p-6 shadow-xl space-y-5 transition-colors">
          
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-150 dark:border-white/5 pb-4">
            <div className="text-left">
              <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Active Subject</h4>
              <p className="text-sm font-semibold text-slate-800 dark:text-slate-200 line-clamp-2 leading-snug">
                {image.originalTopic || image.prompt}
              </p>
            </div>
            {image.level && (
              <div className="flex flex-wrap gap-1.5 shrink-0">
                <span className="text-[10px] font-bold tracking-wider text-cyan-600 dark:text-cyan-400 bg-cyan-50 dark:bg-cyan-950/40 px-2.5 py-1 rounded-full border border-cyan-500/15">
                  {image.level}
                </span>
                {image.style && (
                  <span className="text-[10px] font-bold tracking-wider text-purple-600 dark:text-purple-400 bg-purple-50 dark:bg-purple-950/40 px-2.5 py-1 rounded-full border border-purple-500/15">
                    {image.style}
                  </span>
                )}
                {image.language && (
                  <span className="text-[10px] font-bold tracking-wider text-green-600 dark:text-green-400 bg-green-50 dark:bg-green-950/40 px-2.5 py-1 rounded-full border border-green-500/15">
                    {image.language}
                  </span>
                )}
              </div>
            )}
          </div>

          <div className="space-y-3">
            <h4 className="text-[10px] font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest text-left">Share & Export</h4>
            
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
              {/* Copy Link */}
              <button
                onClick={handleCopyLink}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-cyan-500/40 dark:hover:border-cyan-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-cyan-50/25 dark:hover:bg-cyan-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                {copiedLink ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-500 scale-110 shrink-0" />
                    <span className="text-emerald-600 dark:text-emerald-400">Copied!</span>
                  </>
                ) : (
                  <>
                    <Copy className="w-4 h-4 text-slate-400 group-hover:text-cyan-550 dark:group-hover:text-cyan-400 transition-colors shrink-0" />
                    <span>Copy Link</span>
                  </>
                )}
              </button>

              {/* Copy Image */}
              <button
                onClick={handleCopyImage}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-cyan-500/40 dark:hover:border-cyan-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-cyan-50/25 dark:hover:bg-cyan-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                {copiedImage ? (
                  <>
                    <Check className="w-4 h-4 text-emerald-500 scale-110 shrink-0" />
                    <span className="text-emerald-600 dark:text-emerald-400">Copied Image</span>
                  </>
                ) : (
                  <>
                    <Image className="w-4 h-4 text-slate-400 group-hover:text-cyan-550 dark:group-hover:text-cyan-400 transition-colors shrink-0" />
                    <span>Copy Image</span>
                  </>
                )}
              </button>

              {/* Share X */}
              <button
                onClick={handleTwitterShare}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-sky-500/40 dark:hover:border-sky-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-sky-50/25 dark:hover:bg-sky-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                <Twitter className="w-4 h-4 text-slate-400 group-hover:text-sky-500 transition-colors shrink-0" />
                <span>Share to X</span>
              </button>

              {/* Share LinkedIn */}
              <button
                onClick={handleLinkedInShare}
                className="flex items-center gap-2.5 justify-center px-4 py-3 rounded-xl border border-slate-200 dark:border-white/10 hover:border-blue-500/40 dark:hover:border-blue-500/40 bg-slate-50 dark:bg-slate-950/50 hover:bg-blue-50/25 dark:hover:bg-blue-950/20 text-slate-700 dark:text-slate-300 transition-all font-semibold text-xs group"
              >
                <Linkedin className="w-4 h-4 text-slate-400 group-hover:text-blue-500 transition-colors shrink-0" />
                <span>LinkedIn</span>
              </button>
            </div>

            {isShareApiSupported && (
              <button
                onClick={handleNativeShare}
                className="w-full mt-2 flex items-center gap-2 justify-center py-2.5 rounded-xl border border-dashed border-slate-200 dark:border-white/15 text-xs text-slate-500 hover:text-cyan-500 dark:text-slate-400 dark:hover:text-cyan-400 bg-transparent hover:bg-cyan-50/10 transition-all cursor-pointer"
              >
                <Share2 className="w-3.5 h-3.5" />
                <span>Use Device Native sharing option</span>
              </button>
            )}
          </div>

          <div className="text-center pt-2">
            <p className="text-[10px] text-slate-500 dark:text-slate-500 font-mono max-w-xl mx-auto truncate opacity-60">
              PROMPT: {image.prompt}
            </p>
          </div>

        </div>
      </div>

      {/* Fullscreen Modal */}
      {isFullscreen && (
        <div className="fixed inset-0 z-[100] bg-slate-100/95 dark:bg-slate-950/95 backdrop-blur-xl flex flex-col animate-in fade-in duration-300">
            {/* Toolbar */}
            <div className="absolute top-0 left-0 right-0 p-4 flex justify-between items-center z-50 pointer-events-none">
                <div className="flex gap-2 pointer-events-auto bg-white/10 backdrop-blur-md p-1 rounded-lg border border-black/5 dark:border-white/10">
                    <button onClick={handleZoomOut} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Zoom Out">
                        <ZoomOut className="w-5 h-5" />
                    </button>
                    <button onClick={handleResetZoom} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Reset Zoom">
                        <span className="text-xs font-bold">{Math.round(zoomLevel * 100)}%</span>
                    </button>
                    <button onClick={handleZoomIn} className="p-2 hover:bg-black/10 dark:hover:bg-white/10 rounded-md text-slate-800 dark:text-slate-200 transition-colors" title="Zoom In">
                        <ZoomIn className="w-5 h-5" />
                    </button>
                </div>

                <button 
                    onClick={handleCloseFullscreen}
                    className="pointer-events-auto p-3 bg-slate-200 dark:bg-slate-800 text-slate-900 dark:text-white rounded-full hover:bg-slate-300 dark:hover:bg-slate-700 transition-colors shadow-lg"
                >
                    <X className="w-6 h-6" />
                </button>
            </div>

            <div className="flex-1 overflow-auto flex items-center justify-center p-4 sm:p-8">
                <img 
                    src={image.data} 
                    alt={image.prompt}
                    style={{ 
                        transform: `scale(${zoomLevel})`,
                        transition: 'transform 0.2s ease-out'
                    }}
                    className="max-w-full max-h-full object-contain shadow-2xl rounded-lg origin-center"
                />
            </div>
        </div>
      )}
    </div>
  );
};

export default Infographic;